In [1]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
from sklearn.datasets import load_sample_image
from sklearn.datasets import load_digits
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix, accuracy_score

from scipy.stats import mode

In [2]:
digits = load_digits()
X = digits.data
y = digits.target

In [3]:
km = KMeans(n_clusters=10)

predict = km.fit_predict(X)

In [4]:
labels = np.zeros_like(predict)
for i in range(10):
    mask = (predict==i)
    labels[mask] = mode(y[mask])[0]

In [5]:
print ("Accuracy Score: ", accuracy_score(y,labels))
print ("\nConfusion Matrix: \n", confusion_matrix(y, labels))

Accuracy Score:  0.7952142459654981

Confusion Matrix: 
 [[177   0   0   0   1   0   0   0   0   0]
 [  0  55  24   1   0   1   2   0  99   0]
 [  1   2 148  13   0   0   0   3   8   2]
 [  0   0   1 157   0   2   0   7   7   9]
 [  0   5   0   0 164   0   0   9   3   0]
 [  0   0   0   1   2 136   1   0   0  42]
 [  1   1   0   0   0   0 177   0   2   0]
 [  0   2   0   0   0   0   0 175   2   0]
 [  0   6   3   2   0   4   2   5 100  52]
 [  0  20   0   6   0   4   0   8   2 140]]


In [15]:
nba = load_sample_image("nba.jpg")
ax = plt.axes(xticks=[], yticks=[])
ax.imshow(nba);

C:\Users\Hp\Anaconda3\lib\site-packages\sklearn\datasets\base.py:762: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  images = [imread(filename) for filename in filenames]
C:\Users\Hp\Anaconda3\lib\site-packages\sklearn\datasets\base.py:762: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  images = [imread(filename) for filename in filenames]


AttributeError: Cannot find sample image: nba.jpg

In [16]:
nba.shape

NameError: name 'nba' is not defined